# Generated by Django 6.0 on 2025-12-12 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("registration_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="WifiModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=50)),
                ("signalStrength", models.FloatField()),
                ("speed", models.FloatField()),
                ("price", models.FloatField()),
                ("description", models.TextField(blank=True, null=True)),
                ("rating", models.FloatField(default=0)),
                ("reviewCount", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "WifiModel",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wifiModelId",
                    models.ForeignKey(
                        db_column="wifiModelId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.wifimodel",
                    ),
                ),
            ],
            options={
                "db_table": "Review",
            },
        ),
        migrations.CreateModel(
            name="DataPlan",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                (
                    "wifiModelId",
                    models.ForeignKey(
                        db_column="wifiModelId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.wifimodel",
                    ),
                ),
            ],
            options={
                "db_table": "DataPlan",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wifiModelId",
                    models.ForeignKey(
                        db_column="wifiModelId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.wifimodel",
                    ),
                ),
            ],
            options={
                "db_table": "Favorite",
                "unique_together": {("userId", "wifiModelId")},
            },
        ),
    ]
